sudo: false
dist: trusty

language: java

branches:
  only:
    - master

jdk:
  - oraclejdk8

before_script:
  - mysql -uroot -e "create database doma_gen_it"

env:
  - DB=hsqldb JDBC_URL=jdbc:hsqldb:mem:doma_gen_it JDBC_USER= JDBC_PASSWORD= FACTORY=org.seasar.doma.extension.gen.it.GenItGlobalFactory
  - DB=mysql JDBC_URL=jdbc:mysql://127.0.0.1/doma_gen_it JDBC_USER=travis JDBC_PASSWORD= FACTORY=org.seasar.doma.extension.gen.it.GenItGlobalMySqlFactory

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS doma_gen_it;'; fi"

script:
  - ./gradlew check -info -PjdbcUrl=$JDBC_URL -PjdbcUser=$JDBC_USER -PjdbcPassword=$JDBC_PASSWORD -PglobalFactoryClassName=$FACTORY
